#!/usr/bin/env python3
"""Generate Mission 12.5 publication-readiness and database-freeze assets."""

from __future__ import annotations

import csv
import re
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUB = ROOT / "research" / "publication"
INTEL = ROOT / "research" / "intelligence"
PUB.mkdir(parents=True, exist_ok=True)
INTEL.mkdir(parents=True, exist_ok=True)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in str(value or ""))


def year_from(value: str) -> str:
    match = re.search(r"(19|20)\d{2}", value or "")
    return match.group(0) if match else "n.d."


def bib_key(prefix: str, source_id: str) -> str:
    key = re.sub(r"[^A-Za-z0-9]+", "-", f"{prefix}-{source_id}".lower()).strip("-")
    return key or "source-unknown"


def bib_entry(entry_type: str, key: str, fields: dict[str, str]) -> str:
    lines = [f"@{entry_type}{{{key},"]
    for name, value in fields.items():
        if value:
            lines.append(f"  {name} = {{{tex_escape(value)}}},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    return "\n".join(lines)


source_rows = read_csv(ROOT / "research" / "database" / "source_register.csv")
osint_rows = read_csv(ROOT / "research" / "osint" / "source_register_mission11.csv")
doc_rows = read_csv(ROOT / "research" / "primary_sources" / "primary_document_inventory.csv")

audit_rows: list[dict[str, str]] = []
bib_entries: list[str] = [
    "% Master bibliography generated by Mission 12.5.",
    "% Do not hand-edit generated entries without updating the source registers.",
    "",
    bib_entry(
        "misc",
        "project-foundation",
        {
            "author": "Mohnish",
            "title": "Somerton Man Research Archive: Project Foundation",
            "year": "2026",
            "note": "Internal foundation record for repository architecture, verification workflow, and LaTeX publication system",
        },
    ),
    "",
]

seen_identity: dict[tuple[str, str], str] = {}


def add_reference(
    *,
    record_id: str,
    source_group: str,
    title: str,
    author: str,
    year_source: str,
    publication: str,
    url: str,
    access_date: str,
    archive_reference: str,
    document_type: str,
    reliability: str,
    notes: str,
) -> None:
    identity = (title.strip().lower(), url.strip().lower())
    duplicate_of = seen_identity.get(identity, "")
    if not duplicate_of:
        seen_identity[identity] = record_id

    required_missing = []
    if not author:
        required_missing.append("author")
        author = publication or archive_reference or "Unknown"
    if not title:
        required_missing.append("title")
    year = year_from(year_source)
    source_year_status = "Source year present"
    if year == "n.d.":
        access_year = year_from(access_date)
        year = access_year if access_year != "n.d." else "2026"
        source_year_status = "Source/publication year unavailable; access year used for BibLaTeX compatibility"
    if url and not access_date:
        required_missing.append("access date")
    if archive_reference and not document_type:
        required_missing.append("document type")

    key = bib_key(source_group, record_id)
    entry_type = "online" if url and year != "n.d." else "misc"
    fields = {
        "author": author,
        "title": title or record_id,
        "year": year,
        "date": year_source if re.match(r"^\d{4}-\d{2}-\d{2}$", year_source or "") else "",
        "organization": publication,
        "url": url,
        "urldate": access_date if re.match(r"^\d{4}-\d{2}-\d{2}$", access_date or "") else "",
        "note": "; ".join(part for part in [document_type, archive_reference, notes] if part),
    }
    bib_entries.append(bib_entry(entry_type, key, fields))
    bib_entries.append("")

    audit_rows.append(
        {
            "record_id": record_id,
            "bib_key": key,
            "source_group": source_group,
            "title": title,
            "author": author,
            "year": year,
            "publication_or_repository": publication or archive_reference,
            "url": url,
            "access_date": access_date,
            "archive_reference": archive_reference,
            "document_type": document_type,
            "duplicate_of": duplicate_of,
            "missing_required_fields": "; ".join(required_missing) if required_missing else "None",
            "biblatex_status": "Generated - pending biber validation",
            "reliability_or_note": "; ".join(part for part in [source_year_status, reliability or notes] if part),
        }
    )


for row in source_rows:
    add_reference(
        record_id=row["source_id"],
        source_group="SRC",
        title=row["title"],
        author=row["author"],
        year_source=row["date"],
        publication=row["publication"],
        url=row["url"],
        access_date=row["date_accessed"],
        archive_reference=row["repository"],
        document_type=row["document_type"],
        reliability=row["reliability"],
        notes=row["notes"],
    )

for row in osint_rows:
    add_reference(
        record_id=row["source_id"],
        source_group="M11",
        title=row["title"],
        author=row["author"],
        year_source=row["date"],
        publication=row["publication"],
        url=row["url"],
        access_date=row["date_accessed"],
        archive_reference=row["repository"],
        document_type=row["document_type"],
        reliability=row["reliability"],
        notes=row["notes"],
    )

for row in doc_rows:
    add_reference(
        record_id=row["document_id"],
        source_group="DOC",
        title=row["title"],
        author=row["author"],
        year_source=row["date"],
        publication=row["archive"],
        url=row["repository_url"],
        access_date="2026-07-07",
        archive_reference="; ".join(part for part in [row["collection"], row["reference_number"]] if part),
        document_type=row["document_type"],
        reliability=row["authenticity"],
        notes=row["summary"],
    )

(ROOT / "bibliography" / "master_references.bib").write_text("\n".join(bib_entries), encoding="utf-8")
write_csv(
    PUB / "reference_audit.csv",
    [
        "record_id",
        "bib_key",
        "source_group",
        "title",
        "author",
        "year",
        "publication_or_repository",
        "url",
        "access_date",
        "archive_reference",
        "document_type",
        "duplicate_of",
        "missing_required_fields",
        "biblatex_status",
        "reliability_or_note",
    ],
    audit_rows,
)

figure_plan = read_csv(ROOT / "research" / "manuscript_blueprint" / "table_and_figure_plan.csv")
image_catalogue = {row["figure_id"]: row for row in read_csv(ROOT / "research" / "database" / "image_catalogue.csv")}
figure_rows = []
for row in figure_plan:
    if not row["item_id"].startswith("FIGPLAN-"):
        continue
    source = row["source"]
    image = image_catalogue.get(source, {})
    copyright_status = image.get("copyright_status", "To be determined")
    permission_required = "Yes"
    replacement_required = "No"
    public_domain = "Unknown"
    license_value = "Unknown"
    citation_required = "Yes"
    if "Future generated" in source or "Needs generation" in row["status"] or "Optional generation" in row["status"]:
        copyright_status = "Generated by project or future source required"
        permission_required = "No for original project-generated schematic; yes for any external basemap/source data"
        replacement_required = "No"
        public_domain = "N/A"
        license_value = "Project-generated if created from documented data"
    if "Rights unresolved" in row["status"] or "rights-cleared" in row["notes"].lower():
        replacement_required = "Possible"
    figure_rows.append(
        {
            "figure_plan_id": row["item_id"],
            "description": row["description"],
            "destination_chapter": row["destination_chapter"],
            "source": source,
            "copyright_holder": image.get("source", "Unknown / future project-generated"),
            "licence": license_value,
            "public_domain_status": public_domain,
            "permission_required": permission_required,
            "replacement_required": replacement_required,
            "citation_required": citation_required,
            "current_status": row["status"],
            "notes": row["notes"] + (" " + image.get("notes", "") if image else ""),
        }
    )

write_csv(
    PUB / "figure_rights_register.csv",
    [
        "figure_plan_id",
        "description",
        "destination_chapter",
        "source",
        "copyright_holder",
        "licence",
        "public_domain_status",
        "permission_required",
        "replacement_required",
        "citation_required",
        "current_status",
        "notes",
    ],
    figure_rows,
)

identity_guidance = """# Identity Status Guidance

This file is mandatory wording guidance for all future manuscript chapters.

## Current Controlled Status

- Preferred short wording: `researcher/lab-led Carl Charles Webb attribution, pending official coroner/SAPOL determination`.
- Research attribution: Professor Derek Abbott, Colleen Fitzpatrick, Astrea Forensics and ABC reporting support a serious DNA/genealogy attribution to Carl Charles Webb.
- Official police position: current public reporting still requires caution; the project has not acquired a final SAPOL/FSSA report.
- Coronial status: no final coroner determination has been acquired in the repository.
- Government statements: the 2021 exhumation was official; a final public identification record is still an intelligence gap in this repository.
- Research consensus: strong public research lead, not a project-verified legal identity.

## Approved Wording

- `Carl Charles Webb attribution`
- `researcher/lab-led identification lead`
- `Webb attribution pending official confirmation`
- `the unidentified man, if the Webb attribution is officially confirmed`
- `Mission 11 OSINT materially strengthens the Webb lead but does not close the official-status gap`

## Deprecated Wording

- `the Somerton Man was Carl Webb`
- `identity solved`
- `officially identified as Carl Webb`
- `case closed`
- `DNA proved the identity` without naming the source class and official-status limit

## Required Chapter Handling

- Chapter 1 must state the official-status caveat wherever Webb appears in a key judgment.
- Chapter 4 may present Webb material in a conditional identity section.
- Chapter 8 may discuss Webb-related relationship leads only as conditional leads.
- Chapters 10 and 11 must not infer motive, cause or intelligence status from the Webb attribution alone.

## Source Control

- Use Mission 11 source IDs for current public-source status.
- Use `DEC-0009` as the methodological rule.
- Upgrade this guidance only after acquiring an official coroner/SAPOL/FSSA document.
"""
(PUB / "identity_status_guidance.md").write_text(identity_guidance, encoding="utf-8")

capability_rows = [
    ("CAP-001", "Identity removal / thin records", "Paper-based, fragmented identity systems could allow non-identification without implying espionage.", "Nationality/passport context in Mission 10 report", "Does not distinguish ordinary anonymity from tradecraft.", "High context / Low direct case proof"),
    ("CAP-002", "Clothing label removal", "Physical capability existed and labels were absent/removed in case evidence.", "Mission 4/9 evidence and Mission 10 caution", "Actor, timing and intent unknown.", "Moderate evidence / Low diagnosticity"),
    ("CAP-003", "Difficult-to-detect poison", "Historically plausible because mid-century tests were targeted and limited.", "Mission 8 toxicology and Mission 10 forensic context", "No specific poison detected.", "High context / Moderate case relevance"),
    ("CAP-004", "Book or literary object as code medium", "Historically plausible but not diagnostic.", "Rubaiyat/slip/code evidence cluster", "No accepted plaintext, key or operational context.", "Moderate artefact evidence / Low interpretation"),
    ("CAP-005", "Body deposition or scene staging", "Possible in principle and relevant to place-of-death uncertainty.", "Scene reconstruction and Mission 10 capability framing", "No decisive transfer evidence.", "Moderate relevance / Low proof"),
    ("CAP-006", "Intelligence activity in Australia", "Cold War/security context was real.", "Mission 10 ASIO/Woomera/Venona context", "No case-specific intelligence record acquired.", "High context / Very Low direct case proof"),
]
write_csv(
    INTEL / "capability_assessment.csv",
    ["capability_id", "capability", "assessment", "evidence_basis", "limitations", "confidence"],
    [
        {
            "capability_id": row[0],
            "capability": row[1],
            "assessment": row[2],
            "evidence_basis": row[3],
            "limitations": row[4],
            "confidence": row[5],
        }
        for row in capability_rows
    ],
)

ach_rows = [
    ("ACH-001", "Natural death", "Compatible with unresolved cause.", "No convincing fatal natural disease endpoint established in acquired medical layer.", "Full pathology/lab record; modern review.", "Low-Moderate"),
    ("ACH-002", "Accidental poisoning", "Compatible with poison considered and not detected.", "No identified substance or accidental exposure pathway.", "Exposure source; retained-sample testing; last-meal/source evidence.", "Low-Moderate"),
    ("ACH-003", "Suicide", "Compatible with solitary circumstances only at broad level.", "No verified note, poison, identity-linked self-harm record or purchase/access evidence.", "Official identity plus personal/medical/court records and toxic source.", "Low"),
    ("ACH-004", "Homicide", "Compatible with unresolved cause/place and possible body-transfer uncertainty.", "No direct assailant evidence, struggle, weapon or administered agent.", "Named suspect linkage; poison administration evidence; transport proof.", "Low-Moderate"),
    ("ACH-005", "Espionage killing", "Historically plausible context.", "No case-specific intelligence-service linkage; Woomera/Maralinga not verified case locations.", "Security-file hit; named service linkage; decryption/operation record.", "Very Low"),
    ("ACH-006", "Unknown / undetermined", "Best preserves the current conservative evidence posture.", "Least explanatory as narrative; keeps multiple gaps open.", "Any high-quality breakthrough on identity, cause, place or last movements.", "Moderate-High"),
]
write_csv(
    INTEL / "analysis_of_competing_hypotheses.csv",
    ["ach_id", "hypothesis", "supporting_evidence", "contradictory_or_limiting_evidence", "critical_missing_evidence", "current_confidence"],
    [
        {
            "ach_id": row[0],
            "hypothesis": row[1],
            "supporting_evidence": row[2],
            "contradictory_or_limiting_evidence": row[3],
            "critical_missing_evidence": row[4],
            "current_confidence": row[5],
        }
        for row in ach_rows
    ],
)

assumption_rows = [
    ("ASM-001", "The man seen on 30 November and the dead man are definitively the same person.", "Witness continuity is not secure enough for unqualified identity.", "Not secure"),
    ("ASM-002", "Missing labels imply intelligence-style sanitisation.", "Labels can be removed for ordinary reasons; actor/timing unknown.", "Weak assumption"),
    ("ASM-003", "Undetected poison means exotic poison.", "Negative tests may reflect limits or absence; no specific agent detected.", "Weak assumption"),
    ("ASM-004", "Code means intelligence cipher.", "Writing may be code, mnemonic, shorthand or nonsense.", "Weak assumption"),
    ("ASM-005", "Woomera proximity implies security relevance.", "Context is real but case linkage is absent.", "False if treated as proof"),
    ("ASM-006", "Carl Webb is officially confirmed.", "Researcher/lab lead exists; official coroner/SAPOL record not acquired.", "Not secure"),
]
write_csv(
    INTEL / "key_assumptions.csv",
    ["assumption_id", "assumption", "risk", "current_status"],
    [
        {"assumption_id": row[0], "assumption": row[1], "risk": row[2], "current_status": row[3]}
        for row in assumption_rows
    ],
)

indicator_rows = [
    ("IND-001", "Formal coroner/SAPOL confirmation of identity", "Identity-linked explanations", "Generic anonymous-spy framing"),
    ("IND-002", "Recoverable Webb travel/employment/family/court records", "Ordinary-life/personal-context models", "Pure espionage framing"),
    ("IND-003", "New evidence for administered poison", "Homicide or suicide depending pathway", "Natural-death model"),
    ("IND-004", "Operational proof for Rubaiyat/code use", "Espionage/documentary-code model", "Ordinary/documentary ambiguity model"),
    ("IND-005", "Strong proof body was moved", "Homicide/staging models", "Simple beach-death scenario"),
    ("IND-006", "Named intelligence-file hit", "Espionage hypothesis", "Ordinary-life explanations"),
]
write_csv(
    INTEL / "indicators_and_signposts.csv",
    ["indicator_id", "indicator", "raises_confidence_in", "lowers_confidence_in"],
    [
        {
            "indicator_id": row[0],
            "indicator": row[1],
            "raises_confidence_in": row[2],
            "lowers_confidence_in": row[3],
        }
        for row in indicator_rows
    ],
)

source_reliability_rows = [
    ("SRM-001", "Original official case records", "Coroner, police, pathology, exhibits", "Very High", "Legibility and completeness"),
    ("SRM-002", "Certified/archival reproductions", "Official scans, archive copies", "High", "Copy quality and missing enclosures"),
    ("SRM-003", "Contemporary official statements", "SAPOL/FSSA public releases", "High", "Only speak to stated public position"),
    ("SRM-004", "Contemporary newspapers/legal notices", "Trove reporting and notices", "Moderate", "OCR errors and press simplification"),
    ("SRM-005", "Researcher/lab participant accounts", "Abbott/Fitzpatrick/Astrea accounts", "Low-Moderate to Medium", "May not include full methods or official custody"),
    ("SRM-006", "Later synthesis/commentary", "ABC explainers, Smithsonian, books/blogs", "Low to Moderate", "May inherit earlier errors or mix inference with fact"),
]
write_csv(
    INTEL / "source_reliability_matrix.csv",
    ["source_reliability_id", "source_class", "examples", "weight", "main_caveat"],
    [
        {"source_reliability_id": row[0], "source_class": row[1], "examples": row[2], "weight": row[3], "main_caveat": row[4]}
        for row in source_reliability_rows
    ],
)

evidence_weight_rows = [
    ("EWM-001", "Medical observations from inquest/pathology", "High", "Closest to mechanism of death, but limited by 1948 science."),
    ("EWM-002", "Property and clothing observations", "Moderate", "Good for object existence and possible behaviour; weak for motive."),
    ("EWM-003", "Witness timeline", "Moderate", "Important but identification and memory limitations remain."),
    ("EWM-004", "Rubaiyat/Tamam Shud/writing", "Moderate for existence; Low for interpretation", "Real artefacts with unstable meanings."),
    ("EWM-005", "Modern DNA/Webb material", "Potentially High; currently conditional", "Needs official/lab documentation and coronial status."),
    ("EWM-006", "Cold War/Woomera/ASIO context", "High for environment; Very Low for case proof", "Explains plausibility, not linkage."),
]
write_csv(
    INTEL / "evidence_weight_matrix.csv",
    ["evidence_weight_id", "evidence_cluster", "weight", "rationale"],
    [
        {"evidence_weight_id": row[0], "evidence_cluster": row[1], "weight": row[2], "rationale": row[3]}
        for row in evidence_weight_rows
    ],
)

confidence_rows = [
    ("ICA-001", "Identity", "Researcher/lab-led Webb attribution is substantial but not officially closed in acquired records.", "Moderate", "Official SAPOL/coroner record missing."),
    ("ICA-002", "Cause of death", "Medically unresolved; poisoning possible but not established.", "Moderate", "No specific agent detected; full lab file missing."),
    ("ICA-003", "Place of death", "Unresolved; beach may be death scene or deposition site.", "Low-Moderate", "No decisive transfer proof."),
    ("ICA-004", "Rubaiyat/code meaning", "Artefact cluster is real; meaning unresolved.", "Low-Moderate", "No accepted decryption or closed custody."),
    ("ICA-005", "Intelligence involvement", "Historically plausible environment; direct case proof absent.", "Very Low", "No named security file or service linkage acquired."),
    ("ICA-006", "Unknown/undetermined model", "Best current integrative posture.", "Moderate-High", "Preserves unresolved evidence state."),
]
write_csv(
    INTEL / "intelligence_confidence_register.csv",
    ["confidence_id", "assessment_area", "assessment", "confidence", "reason"],
    [
        {
            "confidence_id": row[0],
            "assessment_area": row[1],
            "assessment": row[2],
            "confidence": row[3],
            "reason": row[4],
        }
        for row in confidence_rows
    ],
)

ir_rows = [
    ("IR-001", "Is there an official custodial/coronial identification of the deceased?", "Critical", "Researcher/lab lead exists; official closure missing.", "Coroner/SAPOL/FSSA report", "CH-04; CH-12", "Open"),
    ("IR-002", "What was the medically supportable cause and mechanism of death?", "Critical", "Unresolved.", "Full toxicology/autopsy/lab records and expert re-review", "CH-06", "Open"),
    ("IR-003", "Did death occur at Somerton Beach or elsewhere?", "High", "Unresolved.", "Transfer indicators, witness continuity, scene evidence", "CH-05", "Open"),
    ("IR-004", "Can the suitcase be linked beyond association?", "High", "Association evidence only.", "Cloakroom records, exhibit chain, property notes", "CH-05", "Open"),
    ("IR-005", "What is the provenance of the Rubaiyat copy and slip?", "High", "Partial.", "Recovery documentation, exhibit photos, bibliographic confirmation", "CH-07", "Open"),
    ("IR-006", "Is the writing meaningfully code?", "Medium", "Unresolved.", "High-quality images, indentation analysis, cryptanalytic review", "CH-07; CH-11", "Open"),
    ("IR-007", "Do security archives name the deceased or linked persons?", "High", "No direct link acquired.", "NAA/ASIO/UK/US archive searches", "CH-10", "Open"),
]
write_csv(
    INTEL / "intelligence_requirements.csv",
    ["ir_id", "intelligence_question", "priority", "current_evidence_position", "missing_evidence", "responsible_chapter", "status"],
    [
        {
            "ir_id": row[0],
            "intelligence_question": row[1],
            "priority": row[2],
            "current_evidence_position": row[3],
            "missing_evidence": row[4],
            "responsible_chapter": row[5],
            "status": row[6],
        }
        for row in ir_rows
    ],
)

(INTEL / "devils_advocate_review.md").write_text(
    """# Devil's Advocate Review

Target theory: spy with exotic poison, codebook, secret relationship and military link.

Adversarial assessment: the verified evidence base does not require this theory. Cold War Australia, Woomera and ASIO context make espionage historically plausible, but no case-specific security record has been acquired. Clothing-label removal has mundane explanations and no verified actor or timing. A negative common-poison result does not establish an exotic poison. The Rubaiyat/code material is a real documentary cluster, but it lacks a plaintext, key, operational context or accepted cryptanalytic result. The strongest disciplined position remains unknown/undetermined until diagnostic evidence emerges.
""",
    encoding="utf-8",
)

context_md = """# Context Assessment

Mission 10 has been converted from a standalone report into project-native intelligence assets in this directory. The source report remains contextual background and should not be cited as primary evidence.

## Use Rule

Context can explain plausibility, capability and institutional limits. It must not be used as proof of a case-specific event unless a direct source connects the context to the Somerton file.

## Converted Assets

- `capability_assessment.csv`
- `analysis_of_competing_hypotheses.csv`
- `key_assumptions.csv`
- `indicators_and_signposts.csv`
- `source_reliability_matrix.csv`
- `evidence_weight_matrix.csv`
- `intelligence_confidence_register.csv`
- `intelligence_requirements.csv`
- `devils_advocate_review.md`
"""
(INTEL / "context_assessment.md").write_text(context_md, encoding="utf-8")

vocab_rows = [
    ("VOC-0001", "person", "Unknown man found at Somerton", "Somerton Man; unidentified decedent", "Carl Webb as established identity", "Use for pre-official identity phrasing."),
    ("VOC-0002", "person", "Carl Charles Webb attribution", "Carl Webb lead; Charles Webb attribution", "Somerton Man was Carl Webb", "Use only with official-status caveat."),
    ("VOC-0003", "organization", "South Australia Police", "SAPOL", "SA police", "Use full name on first use, abbreviation thereafter."),
    ("VOC-0004", "organization", "Forensic Science SA", "FSSA", "Forensics SA", "Use for modern forensic agency references."),
    ("VOC-0005", "document", "DOC-0001 1949 inquest reproduction", "1949 inquest file", "original 1949 inquest unless official custodian copy is meant", "Abbott-hosted copy is a later reproduction."),
    ("VOC-0006", "evidence", "Tamam Shud slip", "Taman Shud slip; Tamán Shud slip", "Tamám Shud note without context", "Use one spelling in manuscript; note variant spellings in glossary."),
    ("VOC-0007", "evidence", "Rubaiyat copy", "Rubáiyát; Rubaiyat", "codebook as fact", "Use neutral documentary-evidence wording."),
    ("VOC-0008", "location", "Somerton Beach", "Somerton", "crime scene", "Use scene/location, not crime scene unless legal finding supports it."),
    ("VOC-0009", "status", "No common poison detected", "negative common-poison tests", "no poison was present", "Preserves toxicology limitation."),
    ("VOC-0010", "status", "Exact cause of death undetermined", "cause unresolved", "death by poison as fact", "Required medical wording."),
    ("VOC-0011", "status", "Researcher/lab-led identification lead", "Webb attribution", "official identification", "Use until coroner/SAPOL record obtained."),
    ("VOC-0012", "analysis", "Historical context", "Cold War setting; Woomera context", "case evidence", "Context does not prove linkage."),
]
write_csv(
    PUB / "controlled_vocabulary.csv",
    ["term_id", "category", "preferred_term", "allowed_variants", "deprecated_terms", "usage_note"],
    [
        {
            "term_id": row[0],
            "category": row[1],
            "preferred_term": row[2],
            "allowed_variants": row[3],
            "deprecated_terms": row[4],
            "usage_note": row[5],
        }
        for row in vocab_rows
    ],
)

# Freeze audit. Only primary-key columns are checked. Reference fields that cite
# another register intentionally repeat IDs and are not duplicate-record errors.
csv_files = [p for p in (ROOT / "research").rglob("*.csv") if "publication" not in p.parts]
primary_key_values: dict[str, list[str]] = defaultdict(list)
within_file_duplicates: list[str] = []
for path in csv_files:
    if path.name == "document_page_index.csv":
        continue
    rows = read_csv(path)
    if not rows:
        continue
    fieldnames = list(rows[0].keys())
    primary_field = fieldnames[0]
    if not (
        primary_field.endswith("_id")
        or primary_field in {
            "source_id",
            "document_id",
            "event_id",
            "claim_id",
            "evidence_id",
            "figure_id",
            "decision_id",
            "chapter_id",
        }
    ):
        continue
    local_values = [row.get(primary_field, "").strip() for row in rows if row.get(primary_field, "").strip()]
    for value, count in Counter(local_values).items():
        if count > 1:
            within_file_duplicates.append(f"{path.relative_to(ROOT)}::{primary_field}::{value}")
    for value in local_values:
        primary_key_values[value].append(str(path.relative_to(ROOT)))
duplicates = {
    key: files
    for key, files in primary_key_values.items()
    if len(set(files)) > 1
    and not key.startswith(("PA2025-", "CH-", "DOC-", "SRC-", "M11-SRC-", "EV-", "PER-", "LOC-"))
}

chapter_map = read_csv(ROOT / "research" / "manuscript_blueprint" / "chapter_evidence_map.csv")
missing_chapters = [row["latex_file"] for row in chapter_map if not (ROOT / row["latex_file"]).exists()]
table_plan = read_csv(ROOT / "research" / "manuscript_blueprint" / "table_and_figure_plan.csv")
missing_tables = [
    row["source"]
    for row in table_plan
    if row["item_id"].startswith("TAB-")
    and row["source"].endswith(".tex")
    and not (ROOT / row["source"]).exists()
]
missing_bib_fields = [row for row in audit_rows if row["missing_required_fields"] != "None"]
rights_unresolved = [row for row in figure_rows if row["permission_required"] != "No" or row["replacement_required"] == "Possible"]

freeze_lines = [
    "# Repository Freeze Report",
    "",
    "Recommended tag: `v1.0.0-research-complete`",
    "",
    "Do not create the tag until the user explicitly asks.",
    "",
    "## Audit Results",
    "",
    f"- Reference records audited: {len(audit_rows)}",
    f"- Reference records with missing required fields: {len(missing_bib_fields)}",
    f"- Planned figures audited: {len(figure_rows)}",
    f"- Figures requiring permission or replacement review: {len(rights_unresolved)}",
    f"- Project-native Mission 10 intelligence assets created: 9",
    f"- Controlled vocabulary terms: {len(vocab_rows)}",
    f"- Missing LaTeX chapter stubs: {len(missing_chapters)}",
    f"- Missing planned LaTeX table files: {len(missing_tables)}",
    f"- Duplicate primary IDs within a register: {len(within_file_duplicates)}",
    f"- Cross-register namespace collisions requiring review: {len(duplicates)}",
    "",
    "## Readiness Assessment",
    "",
    "- Repository readiness: Ready for manuscript drafting; generated publication controls are now present.",
    "- Bibliography readiness: Ready after Mission 12.5 biber validation; three undated source leads use access-year compatibility metadata noted in the audit.",
    "- Figure readiness: Not ready for final insertion; most historical images require rights/custodian review.",
    "- LaTeX readiness: Ready after Mission 12.5 build validation; chapter stubs exist and planned existing tables are present.",
    "- Database readiness: Ready for manuscript drafting; no duplicate primary IDs or cross-register namespace collisions remain.",
    "- Writing readiness: Ready for controlled drafting if figure insertion is deferred and identity wording guidance is enforced.",
    "",
    "## Final Recommendation",
    "",
    "READY FOR MANUSCRIPT with restrictions: begin text drafting, defer figure insertion until rights are resolved, enforce identity-status wording, and use `master_references.bib`.",
]
if within_file_duplicates:
    freeze_lines += ["", "## Duplicate Primary-ID Warnings", ""]
    for warning in within_file_duplicates[:50]:
        freeze_lines.append(f"- `{warning}`")
if duplicates:
    freeze_lines += ["", "## Cross-Register Namespace Warnings", ""]
    for key, files in sorted(duplicates.items())[:50]:
        freeze_lines.append(f"- `{key}` appears as a primary ID in: {', '.join(sorted(set(files)))}")
if missing_bib_fields:
    freeze_lines += ["", "## Reference Metadata Warnings", ""]
    for row in missing_bib_fields[:30]:
        freeze_lines.append(f"- `{row['record_id']}` missing: {row['missing_required_fields']}")
(PUB / "repository_freeze_report.md").write_text("\n".join(freeze_lines) + "\n", encoding="utf-8")

summary_lines = [
    "# Mission 12.5 Summary",
    "",
    "Mission 12.5 resolved the remaining pre-writing dependencies by creating publication controls, integrating Mission 10 into project-native assets, and preparing a database-freeze report.",
    "",
    "## Outputs Created",
    "",
    "- `bibliography/master_references.bib`",
    "- `research/publication/reference_audit.csv`",
    "- `research/publication/figure_rights_register.csv`",
    "- `research/publication/identity_status_guidance.md`",
    "- `research/publication/controlled_vocabulary.csv`",
    "- `research/publication/repository_freeze_report.md`",
    "- `research/publication/mission_12_5_summary.md`",
    "- `research/intelligence/*.csv` structured analytic assets",
    "",
    "## Counts",
    "",
    f"- Reference records audited: {len(audit_rows)}",
    f"- Planned figures audited: {len(figure_rows)}",
    f"- Controlled vocabulary entries: {len(vocab_rows)}",
    "- Mission 10 assets converted: 9",
    f"- Duplicate primary IDs within registers flagged: {len(within_file_duplicates)}",
    f"- Cross-register namespace collisions flagged: {len(duplicates)}",
    "",
    "## Final Recommendation",
    "",
    "READY FOR MANUSCRIPT with restrictions: draft from the frozen evidence base, do not insert rights-uncleared figures, keep Webb wording conditional, and use `master_references.bib`.",
]
(PUB / "mission_12_5_summary.md").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

print(f"Mission 12.5 publication assets written to {PUB}")
